version: "3.9"

services:

  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: health_ia_db
      MYSQL_USER: airflow
      MYSQL_PASSWORD: airflow
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./HealthIABack
    container_name: python_backend
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    environment:
      DB_HOST: mysql
      DB_USER: airflow
      DB_PASSWORD: airflow
      DB_NAME: health_ia_db

  frontend:
    build: ./Frontend
    container_name: vite_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  airflow:
    build: ./airflow
    container_name: airflow
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql+mysqlconnector://airflow:airflow@mysql/health_ia_db

volumes:
  mysql_data: