services:
  mysql:
    image: mysql:8
    container_name: healthia_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: health_ia_db
      MYSQL_USER: healthia
      MYSQL_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10

  backend:
    build: ./HealthIABack
    container_name: healthia_backend
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "5000:5000"
    volumes:
      - ./schema:/app/schema
      - ./Datasets:/Datasets # Monte le dossier Datasets dans le conteneur
    environment:
      DB_HOST: mysql
      DB_USER: healthia
      DB_PASSWORD: 123456
      DB_NAME: health_ia_db
      FLASK_HOST: "0.0.0.0"
      CORS_ALLOWED_ORIGINS: "http://localhost:5173"

  airflow:
    build:
      context: .
      dockerfile: Etl/Dockerfile
    container_name: healthia_airflow
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8081:8080"
    volumes:
      - ./Etl/dags:/opt/airflow/dags
      - ./Datasets:/opt/airflow/Datasets
      - ./HealthIABack/Repositories:/opt/airflow/dags/Repositories
      - ./HealthIABack/Models:/opt/airflow/dags/Models
    environment:
      - DB_HOST=mysql
      - DB_USER=healthia
      - DB_PASSWORD=123456
      - DB_NAME=health_ia_db
    command: standalone

  frontend:
    build: ./Frontend
    container_name: healthia_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
  
  # SUPERVISION DES SERVICES

  mysql-exporter:
    image: prom/mysqld-exporter
    container_name: healthia_mysql_exporter
    command:
      - --config.my-cnf=/etc/mysql/my.cnf
      - --mysqld.address=healthia_mysql:3306
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
    ports:
      - "9104:9104"
    depends_on:
      - mysql

  cadvisor:
      image: gcr.io/cadvisor/cadvisor
      ports:
        - "8082:8080"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /:/rootfs:ro
        - /var/run:/var/run:ro
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro

  prometheus:
      image: prom/prometheus
      ports:
        - "9090:9090"
      volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
      image: grafana/grafana
      ports:
        - "3000:3000"
      depends_on:
        - prometheus

volumes:
  mysql_data:
