version: "3.9"

services:

  mysql:
    image: mysql:8
    container_name: healthia_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: health_ia_db
      MYSQL_USER: healthia
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10

  backend:
    build: ./HealthIABack
    container_name: healthia_backend
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    environment:
      DB_HOST: mysql
      DB_USER: healthia
      DB_PASSWORD: 123456
      DB_NAME: health_ia_db

  airflow:
    build: ./Etl
    container_name: healthia_airflow
    ports:
      - "8080:8080"
    volumes:
      - ./Etl/dags:/opt/airflow/dags
      - ./Datasets:/opt/airflow/datasets
    command: standalone

  frontend:
    build: ./Frontend
    container_name: healthia_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mysql_data:
