sonar.projectKey=Mspr
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/*.sql,**/migrations/**,**/coverage/**,**/dist/**,test-report.xml
sonar.tests=HealthIABack,Frontend
sonar.test.inclusions=**/*Test*.py,**/*.test.js,**/*.test.tsx
