database_type = "mysql"
database_host = "mysql"
database_port = 3306
database_name = "health_ia_db"
database_username = "healthia"
database_password = "123456"

database_table = "pyway_schema_history"

migrations_folder = "/app/schema"
