CREATE TABLE IF NOT EXISTS diet_recommendations (
    id INT AUTO_INCREMENT PRIMARY KEY,
    age tinyint,
    gender INT,
    height_cm SMALLINT ,
    current_weight_kg FLOAT ,
    bmi FLOAT,
    disease_type INT,
    severity INT,
    diet_recommendation  INT,
    daily_caloric_target SMALLINT ,
    activity_level INT,
    created_at TIMESTAMP,
    cholesterol_mg FLOAT,
    blood_pressure_mmhg  SMALLINT,
    glucose_mg_dl  FLOAT ,
    dietary_restrictions INT,
    allergy INT,
    preferred_cuisine INT,
    weekly_exercise_hours FLOAT,
    adherence_to_diet_plan FLOAT ,
    dietary_nutrient_imbalance_score FLOAT,
    FOREIGN KEY (gender) REFERENCES genders(id),
    FOREIGN KEY (disease_type) REFERENCES disease_types(id),
    FOREIGN KEY (severity) REFERENCES severity_types(id),
    FOREIGN KEY (diet_recommendation) REFERENCES diet_recommandation_types(id),
    FOREIGN KEY (activity_level) REFERENCES physical_activity_levels(id),
    FOREIGN KEY (dietary_restrictions) REFERENCES dietary_restrictions(id),
    FOREIGN KEY (allergy) REFERENCES allergies(id),
    FOREIGN KEY (preferred_cuisine) REFERENCES preferred_cuisine_types(id)
)